name: life_style_hub
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  http:
  json_annotation:
  shared_preferences:
  rxdart: # Dart reactive functional programming library
  dio: # a networking library
  path_provider: # Flutter plugin for finding commonly used locations on the filesystem. Supports iOS and Android.
  line_awesome_icons: #for line awesome icons
  image_picker: #for image picking from storage
  progress_dialog:
  sqflite:
  path:
  toast:
  intl: # Library for internationalized/localized messages, date and number formatting
  flutter_spinkit: # progress bar and loading animations
  kiwi:
  random_color:
  moor_flutter:
  provider:
  flutter_colorpicker:
  flutter_local_notifications:
  flare_flutter:
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.7.0
  flutter_vector_icons: ^0.2.1
  video_player:
  chewie:
  chewie_audio:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  logger:


flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/videos/
